export const weatherDetailsData = [
  {
    icon: "humidity",
    progress_bar: 75,
    title: "Влажность",
    value: "75 %",
    text: "",
    initial_value: "0%",
    final_value: "100%",
    hasProgressBar: true,
    hasValues: true,
    hasText: false,
  },
  {
    icon: "pressure",
    progress_bar: "high",
    title: "Давление",
    value: 761,
    text: "Повышенное",
    initial_value: "",
    final_value: "",
    hasProgressBar: true,
    hasValues: false,
    hasText: true,
  },
  {
    icon: "visibility",
    progress_bar: 25,
    title: "Видимость",
    value: "28 км",
    text: "Нормальная",
    initial_value: "",
    final_value: "",
    hasProgressBar: true,
    hasValues: false,
    hasText: true,
  },
  {
    icon: "sunrise",
    progress_bar: 0,
    title: "Рассвет",
    value: "8:42",
    text: "Прошло: 02:47",
    initial_value: "",
    final_value: "",
    hasProgressBar: false,
    hasValues: false,
    hasText: true,
  },
  {
    icon: "sunset",
    progress_bar: 0,
    title: "Закат",
    value: "16:37",
    initial_value: "",
    final_value: "",
    text: "Осталось: 05:08",
    hasProgressBar: false,
    hasValues: false,
    hasText: true,
  },
  {
    icon: "wind",
    progress_bar: 0,
    title: "Сила ветра",
    value: "2 м/с",
    text: "Северо-западный",
    initial_value: "",
    final_value: "",
    hasProgressBar: false,
    hasValues: false,
    hasText: true,
  },
];
