export const weatherDetailsData = [
  {
    icon: 'humidity',
    progress_bar: 75,
    title: 'Влажность',
    value: '75 %',
    text: null,
    initial_value: '0%',
    final_value: '100%',
  },
  {
    icon: 'pressure',
    progress_bar: 'high',
    title: 'Давление',
    value: 761,
    text: 'Повышенное',
    initial_value: null,
    final_value: null,
  },
  {
    icon: 'visibility',
    progress_bar: 25,
    title: 'Видимость',
    value: '28 км',
    text: 'Нормальная',
    initial_value: null,
    final_value: null,
  },
  {
    icon: 'sunrise',
    progress_bar: null,
    title: 'Рассвет',
    value: '8:42',
    text: 'Прошло: 02:47',
    initial_value: null,
    final_value: null,
  },
  {
    icon: 'sunset',
    progress_bar: null,
    title: 'Закат',
    value: '16:37',
    text: 'Осталось: 05:08',
    initial_value: null,
    final_value: null,
  },
  {
    icon: 'wind',
    progress_bar: null,
    title: 'Сила ветра',
    value: '2 м/с',
    text: 'Северо-западный',
    initial_value: null,
    final_value: null,
  },
]
